
import javax.swing.Timer;
import java.util.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.Timer;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author migchav
 */
public class panelMicroondas extends javax.swing.JFrame {

    /**
     * Creates new form panelMicroondas
     */
    public panelMicroondas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        varComida = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        varTiempo = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        boton1 = new javax.swing.JButton();
        boton2 = new javax.swing.JButton();
        boton3 = new javax.swing.JButton();
        boton4 = new javax.swing.JButton();
        boton5 = new javax.swing.JButton();
        boton6 = new javax.swing.JButton();
        boton7 = new javax.swing.JButton();
        boton8 = new javax.swing.JButton();
        boton9 = new javax.swing.JButton();
        boton0 = new javax.swing.JButton();
        botonStart = new javax.swing.JButton();
        botonStop = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(702, 306));
        getContentPane().setLayout(new java.awt.GridLayout());

        jPanel1.setLayout(new java.awt.GridLayout());

        varComida.setText("Aqui la comida");
        varComida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                varComidaActionPerformed(evt);
            }
        });
        jPanel1.add(varComida);

        getContentPane().add(jPanel1);

        jPanel2.setLayout(new java.awt.BorderLayout());

        jPanel3.setLayout(new java.awt.GridLayout());

        varTiempo.setText("Aqui va el tiempo.Pincha aquí con el ratón para borrar el tiempo elegido");
        varTiempo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                varTiempoMouseClicked(evt);
            }
        });
        varTiempo.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                varTiempoPropertyChange(evt);
            }
        });
        jPanel3.add(varTiempo);

        jPanel2.add(jPanel3, java.awt.BorderLayout.PAGE_START);

        jPanel4.setLayout(new java.awt.GridLayout(4, 3));

        boton1.setText("1");
        boton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton1ActionPerformed(evt);
            }
        });
        jPanel4.add(boton1);

        boton2.setText("2");
        boton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton2ActionPerformed(evt);
            }
        });
        boton2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                boton2KeyPressed(evt);
            }
        });
        jPanel4.add(boton2);

        boton3.setText("3");
        boton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton3ActionPerformed(evt);
            }
        });
        jPanel4.add(boton3);

        boton4.setText("4");
        boton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton4ActionPerformed(evt);
            }
        });
        jPanel4.add(boton4);

        boton5.setText("5");
        boton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton5ActionPerformed(evt);
            }
        });
        jPanel4.add(boton5);

        boton6.setText("6");
        boton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton6ActionPerformed(evt);
            }
        });
        jPanel4.add(boton6);

        boton7.setText("7");
        boton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton7ActionPerformed(evt);
            }
        });
        jPanel4.add(boton7);

        boton8.setText("8");
        boton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton8ActionPerformed(evt);
            }
        });
        jPanel4.add(boton8);

        boton9.setText("9");
        boton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton9ActionPerformed(evt);
            }
        });
        jPanel4.add(boton9);

        boton0.setText("0");
        boton0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton0ActionPerformed(evt);
            }
        });
        jPanel4.add(boton0);

        botonStart.setText("Start");
        botonStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonStartActionPerformed(evt);
            }
        });
        jPanel4.add(botonStart);

        botonStop.setText("Stop");
        botonStop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonStopActionPerformed(evt);
            }
        });
        jPanel4.add(botonStop);

        jPanel2.add(jPanel4, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel2);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void varComidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_varComidaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_varComidaActionPerformed

    private void boton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton1ActionPerformed
        String tiempo=varTiempo.getText();
        if(tiempo.equals("Aqui va el tiempo.Pincha aquí con el ratón para borrar el tiempo elegido")) varTiempo.setText("1"); 
        else varTiempo.setText(tiempo+"1");        // TODO add your handling code here:
    }//GEN-LAST:event_boton1ActionPerformed

    private void boton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton3ActionPerformed
        String tiempo=varTiempo.getText();
        if(tiempo.equals("Aqui va el tiempo.Pincha aquí con el ratón para borrar el tiempo elegido")) varTiempo.setText("3"); 
        else varTiempo.setText(tiempo+"3");  
    }//GEN-LAST:event_boton3ActionPerformed

    private void boton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton6ActionPerformed
        String tiempo=varTiempo.getText();
        if(tiempo.equals("Aqui va el tiempo.Pincha aquí con el ratón para borrar el tiempo elegido")) varTiempo.setText("6"); 
        else varTiempo.setText(tiempo+"6"); 
    }//GEN-LAST:event_boton6ActionPerformed

    
    Timer timer = new Timer(1000, new ActionListener(){
    @Override
    public void actionPerformed(ActionEvent e) {
        String tiempo=varTiempo.getText();// TODO add your handling code here:
        int nuevoTiempo=Integer.parseInt(tiempo)-1;
        if(nuevoTiempo<=0) timer.stop();
        varTiempo.setText(String.valueOf(nuevoTiempo));
        }
           
       
        
    });
    private void botonStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonStartActionPerformed
        timer.start();
           
        
    }//GEN-LAST:event_botonStartActionPerformed

    private void botonStopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonStopActionPerformed
       timer.stop(); // TODO add your handling code here:
    }//GEN-LAST:event_botonStopActionPerformed

    private void boton2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_boton2KeyPressed

    }//GEN-LAST:event_boton2KeyPressed

    private void varTiempoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_varTiempoMouseClicked
        // TODO add your handling code here:
        varTiempo.setText("Aqui va el tiempo.Pincha aquí con el ratón para borrar el tiempo elegido");
    }//GEN-LAST:event_varTiempoMouseClicked

    private void boton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton4ActionPerformed
        String tiempo=varTiempo.getText();
        if(tiempo.equals("Aqui va el tiempo.Pincha aquí con el ratón para borrar el tiempo elegido")) varTiempo.setText("4"); 
        else varTiempo.setText(tiempo+"4"); 
    }//GEN-LAST:event_boton4ActionPerformed

    private void boton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton5ActionPerformed
        String tiempo=varTiempo.getText();
        if(tiempo.equals("Aqui va el tiempo.Pincha aquí con el ratón para borrar el tiempo elegido")) varTiempo.setText("5"); 
        else varTiempo.setText(tiempo+"5"); 
    }//GEN-LAST:event_boton5ActionPerformed

    private void boton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton7ActionPerformed
        String tiempo=varTiempo.getText();
        if(tiempo.equals("Aqui va el tiempo.Pincha aquí con el ratón para borrar el tiempo elegido")) varTiempo.setText("7"); 
        else varTiempo.setText(tiempo+"7"); 
    }//GEN-LAST:event_boton7ActionPerformed

    private void boton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton8ActionPerformed
        String tiempo=varTiempo.getText();
        if(tiempo.equals("Aqui va el tiempo.Pincha aquí con el ratón para borrar el tiempo elegido")) varTiempo.setText("8"); 
        else varTiempo.setText(tiempo+"8"); 
    }//GEN-LAST:event_boton8ActionPerformed

    private void boton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton9ActionPerformed
        String tiempo=varTiempo.getText();
        if(tiempo.equals("Aqui va el tiempo.Pincha aquí con el ratón para borrar el tiempo elegido")) varTiempo.setText("9"); 
        else varTiempo.setText(tiempo+"9"); 
    }//GEN-LAST:event_boton9ActionPerformed

    private void boton0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton0ActionPerformed
        String tiempo=varTiempo.getText();
        if(tiempo.equals("Aqui va el tiempo.Pincha aquí con el ratón para borrar el tiempo elegido")) varTiempo.setText("0");
        else varTiempo.setText(tiempo+"0");
    }//GEN-LAST:event_boton0ActionPerformed

    private void boton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton2ActionPerformed
        String tiempo=varTiempo.getText();
        if(tiempo.equals("Aqui va el tiempo.Pincha aquí con el ratón para borrar el tiempo elegido")) varTiempo.setText("2");
        else varTiempo.setText(tiempo+"2");
    }//GEN-LAST:event_boton2ActionPerformed

    private void varTiempoPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_varTiempoPropertyChange

    }//GEN-LAST:event_varTiempoPropertyChange

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(panelMicroondas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(panelMicroondas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(panelMicroondas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(panelMicroondas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new panelMicroondas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton boton0;
    private javax.swing.JButton boton1;
    private javax.swing.JButton boton2;
    private javax.swing.JButton boton3;
    private javax.swing.JButton boton4;
    private javax.swing.JButton boton5;
    private javax.swing.JButton boton6;
    private javax.swing.JButton boton7;
    private javax.swing.JButton boton8;
    private javax.swing.JButton boton9;
    private javax.swing.JButton botonStart;
    private javax.swing.JButton botonStop;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JButton varComida;
    private javax.swing.JLabel varTiempo;
    // End of variables declaration//GEN-END:variables
}
