/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package my.termostatoVista;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.Iterator;
import java.util.List;
import javax.swing.BorderFactory;
import javax.swing.JSpinner;
import my.termostatoModelo.Modelo;
import javax.swing.JSpinner.DefaultEditor;
import javax.swing.WindowConstants;

/**
 *
 * @author migchav,jhocaba,ernperi
 */
public class VistaGest extends javax.swing.JFrame {

    private static Modelo modelo;
    private static ControladorGest control;
    /**
     * Creates new form VistaGest
     */
    public VistaGest(Modelo model) {
        initComponents();
        modelo=model;
        control=new ControladorGest(this,modelo);
        panelText.setBorder(BorderFactory.createEmptyBorder(82, 20, 82, 20)); 
        jPanel4.setBorder(BorderFactory.createEmptyBorder(82, 20, 82, 20)); 
        jPanel3.setBorder(BorderFactory.createEmptyBorder(80, 65, 80, 65)); 
        textProgram.setText(getProgramaComboBox());
        jTextArea1.setWrapStyleWord(true);
        jTextArea1.setLineWrap(true);
        Iterator<String> iterador= modelo.getProgramas().iterator();
        while(iterador.hasNext()){
            comboProgra.addItem(iterador.next());
        }
        ((DefaultEditor) spinMin.getEditor()).getTextField().setEditable(false);
        ((DefaultEditor) spinMax.getEditor()).getTextField().setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        paneltTotal = new javax.swing.JPanel();
        panelInicio = new javax.swing.JPanel();
        btInicio = new javax.swing.JButton();
        panelGest = new javax.swing.JPanel();
        panelSet = new javax.swing.JPanel();
        panelText = new javax.swing.JPanel();
        textProgram = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        btConfirm = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        comboProgra = new javax.swing.JComboBox<>();
        panelAdd = new javax.swing.JPanel();
        panelGen = new javax.swing.JPanel();
        panelInfo = new javax.swing.JPanel();
        panelNombre = new javax.swing.JPanel();
        pNombre2 = new javax.swing.JPanel();
        textNombre = new javax.swing.JTextField();
        panelTemp = new javax.swing.JPanel();
        panelTempMin = new javax.swing.JPanel();
        spinMin = new javax.swing.JSpinner();
        panelTempMax = new javax.swing.JPanel();
        spinMax = new javax.swing.JSpinner();
        panelTiemp = new javax.swing.JPanel();
        panelSele = new javax.swing.JPanel();
        bt1 = new javax.swing.JToggleButton();
        bt2 = new javax.swing.JToggleButton();
        bt3 = new javax.swing.JToggleButton();
        bt4 = new javax.swing.JToggleButton();
        bt5 = new javax.swing.JToggleButton();
        bt6 = new javax.swing.JToggleButton();
        panelVacio = new javax.swing.JPanel();
        panelError = new javax.swing.JPanel();
        textError = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        panelBtConfirm = new javax.swing.JPanel();
        btConfirmAdd = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        paneltTotal.setLayout(new java.awt.BorderLayout());

        panelInicio.setBackground(new java.awt.Color(255, 255, 255));

        btInicio.setBackground(new java.awt.Color(255, 255, 255));
        btInicio.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btInicio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/inicio.png"))); // NOI18N
        btInicio.setText("INICIO");
        btInicio.setFocusable(false);
        btInicio.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btInicio.setIconTextGap(0);
        btInicio.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btInicioActionPerformed(evt);
            }
        });
        panelInicio.add(btInicio);

        paneltTotal.add(panelInicio, java.awt.BorderLayout.NORTH);

        panelGest.setLayout(new java.awt.GridLayout(2, 0));

        panelSet.setBackground(new java.awt.Color(255, 255, 255));
        panelSet.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createEmptyBorder(12, 12, 12, 12), javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1), "SET PROGRAMA", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 32)), javax.swing.BorderFactory.createEmptyBorder(8, 12, 0, 0)))); // NOI18N
        panelSet.setLayout(new java.awt.GridLayout(1, 0));

        panelText.setBackground(new java.awt.Color(255, 255, 255));
        panelText.setLayout(new java.awt.GridLayout(1, 0));

        textProgram.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        textProgram.setText("jTextField1");
        textProgram.setMaximumSize(new java.awt.Dimension(30, 20));
        textProgram.setMinimumSize(new java.awt.Dimension(30, 20));
        textProgram.setPreferredSize(new java.awt.Dimension(30, 20));
        panelText.add(textProgram);

        panelSet.add(panelText);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new java.awt.GridLayout(1, 0));

        btConfirm.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btConfirm.setText("Cambiar Nombre");
        btConfirm.setMaximumSize(new java.awt.Dimension(30, 20));
        btConfirm.setMinimumSize(new java.awt.Dimension(30, 20));
        btConfirm.setPreferredSize(new java.awt.Dimension(30, 20));
        btConfirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btConfirmActionPerformed(evt);
            }
        });
        jPanel3.add(btConfirm);

        panelSet.add(jPanel3);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(new java.awt.GridLayout(1, 0));

        comboProgra.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        comboProgra.setMaximumSize(new java.awt.Dimension(30, 20));
        comboProgra.setMinimumSize(new java.awt.Dimension(30, 20));
        comboProgra.setPreferredSize(new java.awt.Dimension(30, 20));
        comboProgra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboPrograActionPerformed(evt);
            }
        });
        jPanel4.add(comboProgra);

        panelSet.add(jPanel4);

        panelGest.add(panelSet);

        panelAdd.setBackground(new java.awt.Color(255, 255, 255));
        panelAdd.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createEmptyBorder(12, 12, 12, 12), javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1), "AÑADIR PROGRAMAS", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 32)), javax.swing.BorderFactory.createEmptyBorder(8, 12, 0, 0)))); // NOI18N
        panelAdd.setLayout(new java.awt.GridLayout(1, 3, 16, 16));

        panelGen.setBackground(new java.awt.Color(255, 255, 255));
        panelGen.setLayout(new java.awt.GridLayout(1, 0));

        panelInfo.setLayout(new java.awt.GridLayout(2, 1));

        panelNombre.setBackground(new java.awt.Color(255, 255, 255));
        panelNombre.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createCompoundBorder(null, javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1)), javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1), "Nombre:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 16)), javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1)))); // NOI18N
        panelNombre.setLayout(new java.awt.GridLayout(1, 0));

        pNombre2.setLayout(new java.awt.GridLayout(1, 0));

        textNombre.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        textNombre.setForeground(new java.awt.Color(204, 204, 204));
        textNombre.setText("Nombre del programa (No repetido)");
        textNombre.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                textNombreFocusGained(evt);
            }
        });
        textNombre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                textNombreMouseClicked(evt);
            }
        });
        textNombre.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                textNombreInputMethodTextChanged(evt);
            }
        });
        textNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textNombreActionPerformed(evt);
            }
        });
        textNombre.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                textNombrePropertyChange(evt);
            }
        });
        textNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textNombreKeyTyped(evt);
            }
        });
        pNombre2.add(textNombre);

        panelNombre.add(pNombre2);

        panelInfo.add(panelNombre);

        panelTemp.setBackground(new java.awt.Color(255, 255, 255));
        panelTemp.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createCompoundBorder(null, javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1)), javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1), "Temperaturas:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 16)), javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1)))); // NOI18N
        panelTemp.setLayout(new java.awt.GridLayout(1, 0));

        panelTempMin.setBackground(new java.awt.Color(255, 255, 255));
        panelTempMin.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createCompoundBorder(null, javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1)), javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1), "Mínima:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 14)), javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1)))); // NOI18N
        panelTempMin.setLayout(new java.awt.GridLayout(1, 0));

        spinMin.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        spinMin.setModel(new javax.swing.SpinnerNumberModel(0, 0, 45, 1));
        spinMin.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spinMinStateChanged(evt);
            }
        });
        panelTempMin.add(spinMin);

        panelTemp.add(panelTempMin);

        panelTempMax.setBackground(new java.awt.Color(255, 255, 255));
        panelTempMax.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createCompoundBorder(null, javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1)), javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1), "Máxima:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 14)), javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1)))); // NOI18N
        panelTempMax.setLayout(new java.awt.GridLayout(1, 0));

        spinMax.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        spinMax.setModel(new javax.swing.SpinnerNumberModel(1, 1, 45, 1));
        spinMax.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spinMaxStateChanged(evt);
            }
        });
        panelTempMax.add(spinMax);

        panelTemp.add(panelTempMax);

        panelInfo.add(panelTemp);

        panelGen.add(panelInfo);

        panelTiemp.setBackground(new java.awt.Color(255, 255, 255));
        panelTiemp.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createCompoundBorder(null, javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1)), javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1), "Intervalos de tiempo", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 16)), javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1)))); // NOI18N
        panelTiemp.setLayout(new java.awt.GridLayout(1, 0));

        panelSele.setBackground(new java.awt.Color(255, 255, 255));
        panelSele.setLayout(new java.awt.GridLayout(3, 3, 10, 10));

        bt1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        bt1.setText("0-3");
        panelSele.add(bt1);

        bt2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        bt2.setText("4-7");
        panelSele.add(bt2);

        bt3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        bt3.setText("8-11");
        panelSele.add(bt3);

        bt4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        bt4.setText("12-15");
        panelSele.add(bt4);

        bt5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        bt5.setText("16-19");
        panelSele.add(bt5);

        bt6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        bt6.setText("20-23");
        panelSele.add(bt6);

        panelVacio.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout panelVacioLayout = new javax.swing.GroupLayout(panelVacio);
        panelVacio.setLayout(panelVacioLayout);
        panelVacioLayout.setHorizontalGroup(
            panelVacioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 137, Short.MAX_VALUE)
        );
        panelVacioLayout.setVerticalGroup(
            panelVacioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 58, Short.MAX_VALUE)
        );

        panelSele.add(panelVacio);

        panelError.setBackground(new java.awt.Color(255, 255, 255));
        panelError.setLayout(new java.awt.GridLayout(1, 0));

        textError.setBorder(null);
        textError.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        textError.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jTextArea1.setRows(5);
        jTextArea1.setAlignmentX(3.0F);
        jTextArea1.setAlignmentY(1.0F);
        jTextArea1.setBorder(null);
        textError.setViewportView(jTextArea1);

        panelError.add(textError);

        panelSele.add(panelError);

        panelBtConfirm.setBackground(new java.awt.Color(255, 255, 255));
        panelBtConfirm.setLayout(new java.awt.GridLayout(1, 0));

        btConfirmAdd.setBackground(new java.awt.Color(0, 0, 0));
        btConfirmAdd.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        btConfirmAdd.setForeground(new java.awt.Color(255, 255, 255));
        btConfirmAdd.setText("AÑADIR");
        btConfirmAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btConfirmAddActionPerformed(evt);
            }
        });
        panelBtConfirm.add(btConfirmAdd);

        panelSele.add(panelBtConfirm);

        panelTiemp.add(panelSele);

        panelGen.add(panelTiemp);

        panelAdd.add(panelGen);

        panelGest.add(panelAdd);

        paneltTotal.add(panelGest, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(paneltTotal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 936, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(paneltTotal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 691, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void comboPrograActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboPrograActionPerformed
        textProgram.setText(getProgramaComboBox());
    }//GEN-LAST:event_comboPrograActionPerformed

    private void btInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btInicioActionPerformed
        control.procesaNavegaInicio();
    }//GEN-LAST:event_btInicioActionPerformed

    private void btConfirmAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btConfirmAddActionPerformed
        if((!textNombre.getText().equals("Nombre del programa (No repetido)")) && (!textNombre.getText().equals(""))){
            if(modelo.contienePrograma(getNombreProgramaNuevo())){
                jTextArea1.setText("Nombre de programa ya utilizado.Cambielo");
            }
            else{
                if(getIntervalos().contains(Boolean.TRUE)){
                    jTextArea1.setText("¡PROGRAMA AÑADIDO!");
                    control.addPrograma();
                    comboProgra.addItem(getNombreProgramaNuevo());
                }
                else{
                    jTextArea1.setText("Seleccione algún horario predefinido");
                }
                
            }
        }
        else{
            jTextArea1.setText("Introduzca un nombre de programa");
        }
        
        
    }//GEN-LAST:event_btConfirmAddActionPerformed

    private void textNombreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textNombreMouseClicked
        textNombre.setText("");
        textNombre.setForeground(new java.awt.Color(0, 0, 0));
    }//GEN-LAST:event_textNombreMouseClicked

    private void btConfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btConfirmActionPerformed
        control.cambiarPrograma();
        comboProgra.removeAllItems();
        Iterator<String> iterador= modelo.getProgramas().iterator();
        while(iterador.hasNext()){
            comboProgra.addItem(iterador.next());
        }
    }//GEN-LAST:event_btConfirmActionPerformed

    private void spinMinStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spinMinStateChanged
        control.observarTempMinima();
    }//GEN-LAST:event_spinMinStateChanged

    private void spinMaxStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spinMaxStateChanged
        control.observarTempMaxima();
    }//GEN-LAST:event_spinMaxStateChanged

    private void textNombrePropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_textNombrePropertyChange
        jTextArea1.setText("");
    }//GEN-LAST:event_textNombrePropertyChange

    private void textNombreInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_textNombreInputMethodTextChanged
        jTextArea1.setText("");
    }//GEN-LAST:event_textNombreInputMethodTextChanged

    private void textNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textNombreActionPerformed
        jTextArea1.setText("");
    }//GEN-LAST:event_textNombreActionPerformed

    private void textNombreFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textNombreFocusGained
        jTextArea1.setText("");
        textNombre.setText("");
        textNombre.setForeground(new java.awt.Color(0, 0, 0));
    }//GEN-LAST:event_textNombreFocusGained

    private void textNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textNombreKeyTyped
        jTextArea1.setText("");
    }//GEN-LAST:event_textNombreKeyTyped

    public String nuevoProgramaText(){
        return (String) textProgram.getText();
    }
    public String getProgramaComboBox(){
        return (String)comboProgra.getSelectedItem();
    }
    public String getNombreProgramaNuevo(){
        return (String) textNombre.getText();
    }
    
    public int getTemperaturaMinima(){
        return (Integer)spinMin.getValue();
    }
    
    public int getTemperaturaMaxima(){
        return (Integer)spinMax.getValue();
    }
    
    public List<Boolean> getIntervalos(){
       return new ArrayList<Boolean>(Arrays.asList(bt1.isSelected(), bt2.isSelected(), bt3.isSelected(), bt4.isSelected(),bt5.isSelected(),bt6.isSelected()));
    }

    
    public void setTempMaxima(int temp){
        spinMax.setValue(temp);
    }
    
    public void setTempMinima(int temp){
        spinMin.setValue(temp);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton bt1;
    private javax.swing.JToggleButton bt2;
    private javax.swing.JToggleButton bt3;
    private javax.swing.JToggleButton bt4;
    private javax.swing.JToggleButton bt5;
    private javax.swing.JToggleButton bt6;
    private javax.swing.JButton btConfirm;
    private javax.swing.JButton btConfirmAdd;
    private javax.swing.JButton btInicio;
    private javax.swing.JComboBox<String> comboProgra;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JPanel pNombre2;
    private javax.swing.JPanel panelAdd;
    private javax.swing.JPanel panelBtConfirm;
    private javax.swing.JPanel panelError;
    private javax.swing.JPanel panelGen;
    private javax.swing.JPanel panelGest;
    private javax.swing.JPanel panelInfo;
    private javax.swing.JPanel panelInicio;
    private javax.swing.JPanel panelNombre;
    private javax.swing.JPanel panelSele;
    private javax.swing.JPanel panelSet;
    private javax.swing.JPanel panelTemp;
    private javax.swing.JPanel panelTempMax;
    private javax.swing.JPanel panelTempMin;
    private javax.swing.JPanel panelText;
    private javax.swing.JPanel panelTiemp;
    private javax.swing.JPanel panelVacio;
    private javax.swing.JPanel paneltTotal;
    private javax.swing.JSpinner spinMax;
    private javax.swing.JSpinner spinMin;
    private javax.swing.JScrollPane textError;
    private javax.swing.JTextField textNombre;
    private javax.swing.JTextField textProgram;
    // End of variables declaration//GEN-END:variables
    
}
